export const monsters = {
  gnoll: {
    name: "Gnoll",
    health: 5,
    mana: null,
    skills: null,
    shield: 1,
    maxSteps: 5,
    stepsCount: 5,
    weapon: "short_axe",
    isAlive: true,
    inventory: [],
  },

  goblin: {
    name: "Goblin",
    health: 4,
    mana: null,
    skills: null,
    shield: 1,
    maxSteps: 6,
    stepsCount: 6,
    weapon: "dagger",
    isAlive: true,
    inventory: [],
  },

  minotaur: {
    name: "Minotaur",
    health: 8,
    mana: null,
    skills: null,
    shield: 2,
    maxSteps: 3,
    stepsCount: 3,
    weapon: "heavy_club",
    isAlive: true,
    inventory: [],
  },

  lichking: {
    name: "LichKing",
    health: 10,
    mana: 10,
    skills: null,
    shield: 3,
    maxSteps: 5,
    stepsCount: 5,
    weapon: "lich_ward",
    isAlive: true,
    inventory: [],
  },

  ogre: {
    name: "Ogre",
    health: 7,
    mana: null,
    skills: null,
    shield: 2,
    maxSteps: 4,
    stepsCount: 4,
    weapon: "heavy_club",
    isAlive: true,
    inventory: [],
  },

  skeleton: {
    name: "Skeleton",
    health: 5,
    mana: 5,
    skills: null,
    shield: 2,
    maxSteps: 5,
    stepsCount: 5,
    weapon: "fantomatic_sword",
    isAlive: true,
    inventory: [],
  },

  slime: {
    name: "Slime",
    health: 12,
    mana: null,
    skills: null,
    shield: 0,
    maxSteps: 2,
    stepsCount: 2,
    weapon: "fantomatic_sword",
    isAlive: true,
    inventory: [],
  },

  specter: {
    name: "Specter",
    health: 5,
    mana: 5,
    skills: null,
    shield: 2,
    maxSteps: 5,
    stepsCount: 5,
    weapon: "fantomatic_sword",
    isAlive: true,
    inventory: [],
  },

  troll: {
    name: "Troll",
    health: 9,
    mana: null,
    skills: null,
    shield: 2,
    maxSteps: 3,
    stepsCount: 3,
    weapon: "heavy_club",
    isAlive: true,
    inventory: [],
  },

  wyvern: {
    name: "Wyvern",
    health: 7,
    mana: 6,
    skills: null,
    shield: 2,
    maxSteps: 7,
    stepsCount: 7,
    weapon: "heavy_club",
    isAlive: true,
    inventory: [],
  },
};

export const monstersArray = Object.keys(monsters);