export const monsters = {
  gnoll: {
    name: "Gnoll",
    health: 5,
    mana: null,
    skills: null,
    shield: 1,
    maxSteps: 5,
    stepsCount: 5,
    maxAttackAction: 1,
    attackActionCount: 1,
    weapon: "lich_ward",
    isAlive: true,
  },

  goblin: {
    name: "Goblin",
    health: 4,
    mana: null,
    skills: null,
    shield: 1,
    maxSteps: 6,
    stepsCount: 6,
    maxAttackAction: 1,
    attackActionCount: 1,
    weapon: "lich_ward",
    isAlive: true,
  },

  lichKing: {
    name: "Lich King",
    health: 10,
    mana: 10,
    skills: null,
    shield: 3,
    maxSteps: 5,
    stepsCount: 5,
    maxAttackAction: 1,
    attackActionCount: 1,
    weapon: "lich_ward",
    isAlive: true,
  },

  ogre: {
    name: "Ogre",
    health: 7,
    mana: null,
    skills: null,
    shield: 2,
    maxSteps: 4,
    stepsCount: 4,
    maxAttackAction: 1,
    attackActionCount: 1,
    weapon: "heavy_club",
    isAlive: true,
  },

  skeleton: {
    name: "Skeleton",
    health: 5,
    mana: 5,
    skills: null,
    shield: 2,
    maxSteps: 5,
    stepsCount: 5,
    maxAttackAction: 1,
    attackActionCount: 1,
    weapon: "fantomatic_sword",
    isAlive: true,
  },

  specter: {
    name: "Specter",
    health: 5,
    mana: 5,
    skills: null,
    shield: 2,
    maxSteps: 5,
    stepsCount: 5,
    maxAttackAction: 1,
    attackActionCount: 1,
    weapon: "fantomatic_sword",
    isAlive: true,
  },

  troll: {
    name: "Troll",
    health: 8,
    mana: null,
    skills: null,
    shield: 3,
    maxSteps: 3,
    stepsCount: 3,
    maxAttackAction: 1,
    attackActionCount: 1,
    weapon: "heavy_club",
    isAlive: true,
  },
};
